apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: descheduler-operator-group
  namespace: openshift-kube-descheduler-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetNamespaces:
    - openshift-kube-descheduler-operator
