kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: rhel10-ivy-manual
  namespace: openshift
  labels:
    flavor.template.kubevirt.io/medium: 'true'
    os.template.kubevirt.io/rhel10.0: 'true'
    template.kubevirt.io/architecture: amd64
    template.kubevirt.io/type: vm
    workload.template.kubevirt.io/server: 'true'
  annotations:
    description: RHEL 10 Template using the existing rhel10 VolumeSnapshot DataSource.
    iconClass: icon-rhel
    openshift.io/display-name: Red Hat Enterprise Linux 10 (IvyBridge-v2)
    tags: 'kubevirt,virtualmachine,rhel,rhel10'
    template.kubevirt.io/provider: User
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      labels:
        app: '${NAME}'
        vm.kubevirt.io/template: rhel10-ivy-manual
      name: '${NAME}'
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: '${NAME}'
          spec:
            sourceRef:
              kind: DataSource
              name: rhel10
              namespace: openshift-virtualization-os-images
            storage:
              resources:
                requests:
                  storage: 30Gi
      runStrategy: Halted
      template:
        metadata:
          labels:
            kubevirt.io/domain: '${NAME}'
        spec:
          domain:
            cpu:
              cores: 1
              sockets: 1
              threads: 1
              model: IvyBridge-v2
              features:
                - name: vmx-rdseed-exit
                  policy: disable
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
            memory:
              guest: 4Gi
          networks:
            - name: default
              pod: {}
          volumes:
            - dataVolume:
                name: '${NAME}'
              name: rootdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  user: cloud-user
                  password: ${CLOUD_USER_PASSWORD}
              name: cloudinitdisk
parameters:
  - name: NAME
    description: Name for the new VM
    generate: expression
    from: 'rhel10-[a-z0-9]{6}'
  - name: CLOUD_USER_PASSWORD
    description: Password for cloud-user
    generate: expression
    from: '[a-z0-9]{8}'
