apiVersion: v1
kind: Node
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  labels:
    coe.muc.redhat.com/second-nic: eno2
    topology.kubernetes.io/zone: muc-a
    node.kubernetes.io/instance-type: "Dell-PowerEdge-R730"
    beta.kubernetes.io/instance-type: "Dell-PowerEdge-R730"
    failure-domain.beta.kubernetes.io/zone: muc-a
    node-role.kubernetes.io/virt-node: ""
  name: storm2
spec: {}
