apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addtional-cluster-gitops-privileges
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - patch
- apiGroups:
  - metallb.io
  resources:
  - metallbs
  - ipaddresspools
  - l2advertisements
  verbs:
  - patch
  - create
- apiGroups:
  - nmstate.io
  resources:
  - nodenetworkconfigurationpolicies
  - nmstates
  verbs:
  - patch
  - create
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - patch
  - create
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - patch
  - create
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - patch
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - patch
  - create
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  - secrets
  verbs:
  - patch
  - create
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - patch
  - create
- apiGroups:
  - trident.netapp.io
  resources:
  - tridentbackendconfigs
  - tridentorchestrators
  verbs:
  - patch
  - create
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - patch
  - create
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - configs
  verbs:
  - patch
  - create
- apiGroups:
  - hco.kubevirt.io
  resources:
  - hyperconvergeds
  verbs:
  - patch
  - create
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclusterhubs
  verbs:
  - patch
  - create
- apiGroups:
  - automationcontroller.ansible.com
  resources:
  - automationcontrollers
  verbs:
  - patch
  - create
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedclusters
  - nodepools
  verbs:
  - patch
  - create
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - patch
  - create
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - patch
  - create
- apiGroups:
  - 'lvm.topolvm.io'
  resources:
  - lvmclusters
  verbs:
  - patch
  - create
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - storageprofiles
  verbs:
  - patch
  - create
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agentserviceconfigs
  verbs:
  - patch
  - create
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  verbs:
  - patch
  - create
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - '*'
- apiGroups:
  - k8s.keycloak.org
  resources:
  - keycloaks
  verbs:
  - patch
  - create
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - patch
  - create
- apiGroups:
  - metal3.io
  resources:
  - provisionings
  verbs:
  - patch
  - create
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - patch
  - create
- apiGroups:
  - forklift.konveyor.io
  resources:
  - forkliftcontrollers
  - providers
  verbs:
  - patch
  - create
- apiGroups:
  - quay.redhat.com
  resources:
  - quayregistries
  verbs:
  - patch
  - create
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - patch
  - create
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims
  verbs:
  - patch
  - create
- apiGroups:
  - observability.open-cluster-management.io
  resources:
  - multiclusterobservabilities
  verbs:
  - patch
  - create
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - '*'
  verbs:
  - patch
  - create
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - '*'
  verbs:
  - patch
  - create
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - patch
  - create
- apiGroups:
  - pool.kubevirt.io
  resources:
  - virtualmachinepools
  verbs:
  - patch
  - create
