apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: cluster
spec:
  templates:
    error:
        name: errors-template
    login:
        name: login-template
    providerSelection:
        name: providers-template
