kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  name: bm-mgmt-storm6
  namespace: openshift-workload-availability
spec:
  data:
#        mgmt_host: "{{ ansible_host }}"
#        mgmt_protocol: "{{ mmgt_protocol | default('redfish') }}"
#        redfish_system_id: "{{ redfish_system_id }}"
#        mgmt_user: "{{ mgmt_user }}"
#        mgmt_password: "{{ mgmt_password }}"

  - remoteRef:
      key: coe-lab/bm-mgmt/storm6-mgmt
      property: mgmt_host
    secretKey: mgmt_host
  - remoteRef:
      key: coe-lab/bm-mgmt/storm6-mgmt
      property: mgmt_user
    secretKey: mgmt_user
  - remoteRef:
      key: coe-lab/bm-mgmt/storm6-mgmt
      property: mgmt_password
    secretKey: mgmt_password
  - remoteRef:
      key: coe-lab/bm-mgmt/storm6-mgmt
      property: redfish_system_id
    secretKey: redfish_system_id
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: bm-mgmt-storm6
    template:
      templateFrom:
        - secret:
            name: bmc-creds-template
            items:
              - key: '--ip'
              - key: '--username'
              - key: '--password'
              - key: '--systems-uri'
