apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: auto-sizing-reserved
spec:
  autoSizingReserved: true 
  machineConfigPoolSelector:
    matchLabels:
      coe.redhat.com/kubeletconfig-auto-sizing-reserved: "true"
