apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rhel9-vuln-scan.yaml
  - rhel10-vuln-scan.yaml

configMapGenerator:
  - name: ansible-ssh-pubkey
    namespace: openshift
    literals:
      - public-key=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ6TCuwHwdK4IQrtLEIwZgopQgaIALn0shN+nJqcBwLl ansible@security-aap
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/part-of: hyperconverged-cluster
        app.kubernetes.io/component: templating

replacements:
  - source:
      kind: ConfigMap
      name: ansible-ssh-pubkey
      fieldPath: data.public-key
    targets:
      - select:
          kind: Template
        fieldPaths:
          - parameters.[name=ANSIBLE_SSH_PUBLIC_KEY].value
