apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 70-worker-enable-lldapd
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: lldpad.service
          enabled: true
          state: started