apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: cluster
spec:
  templates:
    error:
        name: errors-template
    login:
        name: login-template
    providerSelection:
        name: providers-template
  identityProviders:
  - mappingMethod: add
    name: COE-SSO
    openID:
      ca:
        name: openid-ca-gnmjm
      claims:
        email:
        - email
        groups:
        - groups
        name:
        - name
        preferredUsername:
        - preferred_username
      clientID: oauth-openshift.apps.isar.coe.muc.redhat.com
      clientSecret:
        name: openid-client-secret-9sdwg
      issuer: https://sso.coe.muc.redhat.com/realms/coe-sso
    type: OpenID
  - mappingMethod: add
    name: COE-SSO-Admin
    openID:
      ca:
        name: openid-ca-gnmjm
      claims:
        email:
        - email
        groups:
        - groups
        name:
        - name
        preferredUsername:
        - preferred_username
      clientID: oauth-openshift.apps.isar.coe.muc.redhat.com
      clientSecret:
        name: openid-client-secrot-coe-sso-admin
      issuer: https://sso.coe.muc.redhat.com/realms/coe-sso-admin
    type: OpenID
  - htpasswd:
      fileData:
        name: htpasswd-sbh7j
    mappingMethod: claim
    name: Local
    type: HTPasswd
  - google:
      clientID: 1079812798374-5boqg26urlclfrp0cqvsoj3ans6cua6f.apps.googleusercontent.com
      clientSecret:
        name: google-client-secret
      hostedDomain: redhat.com
    mappingMethod: add
    name: RedHatSSO
    type: Google
