apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-of-apps
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - operator: metallb
          - operator: ocp-v
          - operator: nmstate
          - operator: openshift-storage
          - operator: acm
          # Disabled because installed by hand
          # - operator: aap
          - operator: mtv
          - operator: quay
          - operator: acs
  template:
    metadata:
      name: 'operator-{{ operator }}'
      namespace: openshift-gitops
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: default
      source:
        path: 'isar-apps/{{ operator }}/'
        repoURL: https://github.com/stormshift/clusters.git
        targetRevision: main
