apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  applicationMenu:
    section: Red Hat Applications
    imageURL: 'https://raw.githubusercontent.com/stormshift/clusters/refs/heads/main/assets/Technology_icon-Red_Hat-Advanced_Cluster_Security_for_Kubernetes-Standard-RGB.svg'
  href: https://rhacs.coe.muc.redhat.com
  location: ApplicationMenu
  text: 'Red Hat Advanced Cluster Security for Kubernetes'
