apiVersion: v1
data:
  rbac.yaml: |
    name: OpenShift Authentication
    minimumRole: None
    uiEndpoint: rhacs.coe.muc.redhat.com:443
    groups:
        - key: groups
          value: idp-coe-sso-admin
          role: Analyst
        - key: groups
          value: idp-coe-sso
          role: Analyst
        - key: groups
          value: coe-sso-admin
          role: Admin
        - key: groups
          value: global-cluster-admins
          role: Admin
        - key: groups
          value: global-cluster-reader
          role: Analyst
    openshift:
        enable: true
kind: ConfigMap
metadata:
  name: declarative-oauth
  namespace: rhacs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
