apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: rhacs-secured-cluster-services
  namespace: rhacs
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  clusterName: 'local-cluster'
  centralEndpoint: 'central.rhacs.svc:443'
  admissionControl:
    listenOnCreates: true
    listenOnEvents: true
    listenOnUpdates: true
  overlays:
    - apiVersion: apps/v1
      kind: Deployment
      name: sensor
      patches:
        - path: spec.template.spec.containers[name:sensor].env[-1]
          value: |
            name: ROX_VIRTUAL_MACHINES
            value: "true"
    - apiVersion: apps/v1
      kind: DaemonSet
      name: collector
      patches:
        - path: spec.template.spec.containers[name:compliance].env[-1]
          value: |
            name: ROX_VIRTUAL_MACHINES
            value: "true"
