---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
  labels:
    operators.coreos.com/advanced-cluster-management.open-cluster-management: ''
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: release-2.14
  installPlanApproval: Manual
  name: advanced-cluster-management
