apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: coe-bridge-via-enp65s0f1
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  desiredState:
    interfaces:
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp65s0f1
      description: Linux Brige info COE Network via enp65s0f1
      ipv4:
        enabled: false
      name: coe-bridge
      state: up
      type: linux-bridge

  nodeSelector:
    coe.muc.redhat.com/second-nic: enp65s0f1
