apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: virt-node-ucs-c460-m4
spec:
  machineConfigSelector:
    matchExpressions:
      - key: "machineconfiguration.openshift.io/role"
        operator: "In"
        values: 
          - worker
          - virt-node
          - cisco-ucs-c460-m4
  maxUnavailable: 1
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/virt-node
        operator: Exists
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
          - Cisco-UCS-C460-M4
  paused: false
