apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: virt-node
  labels:
    coe.redhat.com/kubeletconfig-set-max-pods: "true"
    coe.redhat.com/kubeletconfig-auto-sizing-reserved: "true"
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,virt-node]}
  maxUnavailable: 1
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/virt-node
        operator: Exists
      - key: node.kubernetes.io/instance-type
        operator: NotIn
        values:
          - Cisco-UCS-C460-M4
  paused: false
