apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: aap
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  applicationMenu:
    section: Red Hat Applications
    imageURL: 'https://raw.githubusercontent.com/stormshift/clusters/refs/heads/main/assets/Technology_icon-Red_Hat-Ansible_Automation_Platform-Standard-RGB.svg'
  href: https://aap.coe.muc.redhat.com
  location: ApplicationMenu
  text: 'Ansible Automation Platform'
