---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
   annotations:
      argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
   namespace: open-cluster-management
   name: hub
spec:
   overrides:
    components:
      - configOverrides: {}
        enabled: true
        name: console
      - configOverrides: {}
        enabled: true
        name: insights
      - configOverrides: {}
        enabled: true
        name: grc
      - configOverrides: {}
        enabled: true
        name: cluster-lifecycle
      - configOverrides: {}
        enabled: true
        name: volsync
      - configOverrides: {}
        enabled: true
        name: multicluster-engine
      - configOverrides: {}
        enabled: true
        name: search
      - configOverrides: {}
        enabled: true
        name: app-lifecycle
      - configOverrides: {}
        enabled: false
        name: cluster-backup
      - configOverrides: {}
        enabled: true
        name: cluster-permission
      - configOverrides: {}
        enabled: true
        name: multicluster-observability
      - configOverrides: {}
        enabled: true
        name: submariner-addon
      - configOverrides: {}
        enabled: false
        name: siteconfig
      - configOverrides: {}
        enabled: false
        name: edge-manager-preview
      - configOverrides: {}
        enabled: false
        name: fine-grained-rbac-preview
