kind: ForkliftController
apiVersion: forklift.konveyor.io/v1beta1
metadata:
  name: forklift-controller
  namespace: openshift-mtv
spec:
  feature_ocp_live_migration: 'true'
  feature_ui_plugin: 'true'
  feature_validation: 'true'
  feature_volume_populator: 'true'
