---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-bundle-secret2
  namespace: quay-enterprise
spec:
  data:
  - remoteRef:
      key: coe-lab/certificate/quay.coe.muc.redhat.com
      property: cert_and_intermediate_pem
    secretKey: crt
  - remoteRef:
      key: coe-lab/certificate/quay.coe.muc.redhat.com
      property: key
    secretKey: key
  - remoteRef:
      key: coe-lab/quay-coe-cert
      property: storage.access_key
    secretKey: storage_access_key
  - remoteRef:
      key: coe-lab/quay-coe-cert
      property: storage.secret_key
    secretKey: storage_secret_key
  - remoteRef:
      key: coe-lab/quay-coe-cert
      property: sso.client_secret
    secretKey: sso_client_secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: config-bundle-secret2
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        config.yaml: |
          DISABLE_PUSHES: false
          ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
          AUTHENTICATION_TYPE: Database
          DEFAULT_TAG_EXPIRATION: 2w
          FEATURE_BUILD_SUPPORT: false
          FEATURE_DIRECT_LOGIN: true
          FEATURE_MAILING: false
          FEATURE_REPO_MIRROR: true
          FEATURE_PROXY_CACHE: true
          FEATURE_QUOTA_MANAGEMENT: true
          FEATURE_ANONYMOUS_ACCESS: true
          FEATURE_UI_V2: true
          FEATURE_UI_V2_REPO_SETTINGS: true
          FEATURE_AUTO_PRUNE: true
          ROBOTS_DISALLOW: false
          REGISTRY_TITLE: Red Hat Quay ISAR/COE
          REGISTRY_TITLE_SHORT: Quay ISAR/COE
          SERVER_HOSTNAME: quay.coe.muc.redhat.com
          SETUP_COMPLETE: true
          TEAM_RESYNC_STALE_TIME: 60m
          TESTING: false
          DISTRIBUTED_STORAGE_CONFIG:
            local_us:
            - RHOCSStorage
            - access_key: {{ .storage_access_key }}
              bucket_name: registry-quay-datastore-rg-fa0c480b-d7eb-4dc9-8d23-fefd58ee921d
              hostname: ocs-storagecluster-cephobjectstore-secure-openshift-storage.apps.isar.coe.muc.redhat.com
              is_secure: true
              port: 443
              secret_key: {{ .storage_secret_key }}
              storage_path: /datastorage/registry
          DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
          - local_us
          DISTRIBUTED_STORAGE_PREFERENCE:
          - local_us
          SUPER_USERS:
            - admin
            - quayadmin
            - rbohne
            - dfroehli
          RHSSO_LOGIN_CONFIG:
            CLIENT_ID: quay-enterprise-isar
            CLIENT_SECRET: {{ .sso_client_secret }}
            OIDC_SERVER: https://sso.coe.muc.redhat.com/realms/coe-sso/
            SERVICE_NAME: RedHatSSO
            SERVICE_ICON: /static/img/RedHat.svg
            VERIFIED_EMAIL_CLAIM_NAME: email
            PREFERRED_USERNAME_CLAIM_NAME: preferred_username
            LOGIN_SCOPES:
              - 'openid'
        ssl.cert: "{{ .crt }}"
        ssl.key: "{{ .key }}"
