apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: registry
  namespace: quay-enterprise
spec:
    configBundleSecret: config-bundle-secret2
    components:
    - kind: quay
      managed: true
    - kind: postgres
      managed: true
    - kind: clair
      managed: true
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: objectstorage
      managed: false
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: clairpostgres
      managed: true
    - kind: route
      managed: true
    - kind: tls
      managed: false
