apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addtional-cluster-gitops-privileges
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - patch
- apiGroups:
  - metallb.io
  resources:
  - metallbs
  - ipaddresspools
  verbs:
  - patch
  - create
- apiGroups:
  - nmstate.io
  resources:
  - nodenetworkconfigurationpolicies
  - nmstates
  verbs:
  - patch
  - create
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - patch
  - create
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - patch
  - create
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - patch
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - patch
  - create
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - patch
  - create
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - patch
  - create
- apiGroups:
  - trident.netapp.io
  resources:
  - tridentbackendconfigs
  - tridentorchestrators
  verbs:
  - patch
  - create
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - configs
  verbs:
  - patch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - addontemplates
  verbs:
  - patch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - patch

